create user 'user'@'%' identified with mysql_native_password by '1234';
grant all privileges on *.* to 'user'@'%' with grant option;
flush privileges;

CREATE TABLE board
(
	number int not null auto_increment primary key,
    title char(150) not null,
    content text not null,
    User_id char(20) not null,
    date datetime not null,
	hit int not null default 0
);

CREATE TABLE user (
  Use_id CHAR(20) NOT NULL primary key,
  Use_pw CHAR(20) NOT NULL,
  Name CHAR(4) NOT NULL,
  Email CHAR(30),
  P_Num CHAR(20) NOT NULL,
  Birth INT,
  Score INT,
  Stage CHAR(10),
  Ranking INT,
  Game_date CHAR(50)
);

CREATE TABLE word (
  Word CHAR(30) NOT NULL PRIMARY KEY,
  Mean CHAR(30) NOT NULL
);

use mydb;
INSERT INTO manager VALUES("1234", "1234");
INSERT INTO word VALUES("persuade", "설득하다", "1234");
INSERT INTO word VALUES("gaze", "응시하다", "1234");
INSERT INTO word VALUES("restore", "회복시키다", "1234");
INSERT INTO word VALUES("heal", "고치다", "1234");
INSERT INTO word VALUES("acquire", "얻다", "1234");
INSERT INTO word VALUES("halt", "서다; (정지)", "1234");
INSERT INTO word VALUES("maintain", "유지, 주장", "1234");
INSERT INTO word VALUES("mourn", "슬퍼하다", "1234");
INSERT INTO word VALUES("suspect", "의심하다", "1234");
INSERT INTO word VALUES("grumble", "불평하다", "1234");
INSERT INTO word VALUES("entertain", "즐겁게 하다", "1234");
INSERT INTO word VALUES("utilize", "이용하다", "1234");
INSERT INTO word VALUES("convert", "바꾸다", "1234");
INSERT INTO word VALUES("despise", "경멸하다", "1234");
INSERT INTO word VALUES("commence", "시작하다", "1234");
INSERT INTO word VALUES("consume", "소비하다", "1234");
INSERT INTO word VALUES("assimilate", "동화하다", "1234");
INSERT INTO word VALUES("impose", "부과, 강요", "1234");
INSERT INTO word VALUES("encounter", "만나다", "1234");
INSERT INTO word VALUES("release", "해방, 면제", "1234");
INSERT INTO word VALUES("specialize", "전공, 전문화", "1234");
INSERT INTO word VALUES("respond", "응답하다", "1234");
INSERT INTO word VALUES("soar", "치솟다", "1234");
INSERT INTO word VALUES("comprehend", "이해, 포함", "1234");
INSERT INTO word VALUES("detect", "발견하다", "1234");
INSERT INTO word VALUES("qualify", "자격을 주다", "1234");
INSERT INTO word VALUES("decorate", "장식하다", "1234");
INSERT INTO word VALUES("accelerate", "속도를 더하다", "1234");
INSERT INTO word VALUES("betray", "배반, 누설", "1234");
INSERT INTO word VALUES("dominate", "통치, 지배", "1234");
INSERT INTO word VALUES("preserve", "유지, 보존", "1234");
INSERT INTO word VALUES("entreat", "간청하다", "1234");
INSERT INTO word VALUES("lack", "부족하다", "1234");
INSERT INTO word VALUES("interrupt", "방해, 중단", "1234");
INSERT INTO word VALUES("surpass", "우월하다", "1234");
INSERT INTO word VALUES("render", "되게 하다, 주다", "1234");
INSERT INTO word VALUES("export", "수출하다", "1234");
INSERT INTO word VALUES("fulfill", "실행하다", "1234");
INSERT INTO word VALUES("inspect", "검사하다", "1234");
INSERT INTO word VALUES("indulge", "탐닉하다", "1234");
INSERT INTO word VALUES("prevail", "유행, 우세", "1234");
INSERT INTO word VALUES("adjust", "적응시키다", "1234");
INSERT INTO word VALUES("estimate", "평가하다", "1234");
INSERT INTO word VALUES("compensate", "배상하다", "1234");
INSERT INTO word VALUES("restrain", "제한하다", "1234");
INSERT INTO word VALUES("appreciate", "감상, 감사", "1234");
INSERT INTO word VALUES("insist", "주장하다", "1234");
INSERT INTO word VALUES("acknowledge", "인정하다", "1234");
INSERT INTO word VALUES("distinguish", "구별하다", "1234");
INSERT INTO word VALUES("involve", "포함하다", "1234");
INSERT INTO word VALUES("intrude", "침입하다", "1234");
INSERT INTO word VALUES("torment", "고문하다", "1234");
INSERT INTO word VALUES("exhaust", "지치게 하다", "1234");
INSERT INTO word VALUES("endure", "견디다", "1234");
INSERT INTO word VALUES("hesitate", "주저하다", "1234");
INSERT INTO word VALUES("substitute", "대신, 대리", "1234");
INSERT INTO word VALUES("prohibit", "금하다", "1234");
INSERT INTO word VALUES("forbid", "금하다", "1234");
INSERT INTO word VALUES("display", "진열, 전시", "1234");
INSERT INTO word VALUES("concentrate", "집중하다", "1234");
INSERT INTO word VALUES("yearn", "그리워하다", "1234");
INSERT INTO word VALUES("forsake", "버리다", "1234");
INSERT INTO word VALUES("endeavor", "노력하다", "1234");
INSERT INTO word VALUES("soothe", "위로하다", "1234");
INSERT INTO word VALUES("congratulate", "축하하다", "1234");
INSERT INTO word VALUES("confuse", "혼란 시키다", "1234");
INSERT INTO word VALUES("improve", "개선하다", "1234");
INSERT INTO word VALUES("diffuse", "보급하다", "1234");
INSERT INTO word VALUES("alter", "바꾸다", "1234");
INSERT INTO word VALUES("speculate", "사색, 투기", "1234");
INSERT INTO word VALUES("recover", "회복하다", "1234");
INSERT INTO word VALUES("urge", "역설하다", "1234");
INSERT INTO word VALUES("command", "명령, 지휘", "1234");
INSERT INTO word VALUES("warn", "경고하다", "1234");
INSERT INTO word VALUES("transport", "수송하다", "1234");
INSERT INTO word VALUES("ignore", "무시하다", "1234");
INSERT INTO word VALUES("conceal", "감추다", "1234");
INSERT INTO word VALUES("utter", "말하다, 완전한", "1234");
INSERT INTO word VALUES("flatter", "아첨하다", "1234");
INSERT INTO word VALUES("absorb", "흡수, 열중", "1234");
INSERT INTO word VALUES("yield", "양보, 굴복", "1234");
INSERT INTO word VALUES("meditate", "숙고하다", "1234");
INSERT INTO word VALUES("perform", "수행, 연기", "1234");
INSERT INTO word VALUES("embarrass", "난처하게 하다", "1234");
INSERT INTO word VALUES("reproach", "비난하다", "1234");
INSERT INTO word VALUES("bewilder", "당황케 하다", "1234");
INSERT INTO word VALUES("overcome", "극복하다", "1234");
INSERT INTO word VALUES("assert", "주장하다", "1234");
INSERT INTO word VALUES("recognize", "인식하다", "1234");
INSERT INTO word VALUES("admit", "인정하다", "1234");
INSERT INTO word VALUES("presecute", "박해하다", "1234");
INSERT INTO word VALUES("launch", "진수, 시작", "1234");
INSERT INTO word VALUES("pretend", "~인 체하다", "1234");
INSERT INTO word VALUES("circulate", "순환, 유통", "1234");
INSERT INTO word VALUES("contemplate", "깊이 생각하다", "1234");
INSERT INTO word VALUES("cope", "맞서다", "1234");
INSERT INTO word VALUES("adapt", "적응시키다", "1234");
INSERT INTO word VALUES("alarm", "놀라게하다", "1234");
INSERT INTO word VALUES("adopt", "채용, 양자삼다", "1234");
INSERT INTO word VALUES("submit", "복종시키다", "1234");
INSERT INTO word VALUES("convince", "확신시키다", "1234");
INSERT INTO word VALUES("repent", "후회하다", "1234");
INSERT INTO word VALUES("predict", "예언하다", "1234");
INSERT INTO word VALUES("avoid", "피하다", "1234");
INSERT INTO word VALUES("boast", "자랑하다", "1234");
INSERT INTO word VALUES("participate", "참가하다", "1234");
INSERT INTO word VALUES("abolish", "페지하다", "1234");
INSERT INTO word VALUES("attribute", "탓으로 돌리다", "1234");
INSERT INTO word VALUES("survey", "조사하다", "1234");
INSERT INTO word VALUES("invest", "투자하다", "1234");
INSERT INTO word VALUES("seek", "구하다", "1234");
INSERT INTO word VALUES("communicate", "전달하다, 소통하다", "1234");
INSERT INTO word VALUES("perplex", "당황케 하다", "1234");
INSERT INTO word VALUES("broadcast", "방송하다", "1234");
INSERT INTO word VALUES("reject", "거절하다", "1234");
INSERT INTO word VALUES("vex", "괴롭히다", "1234");
INSERT INTO word VALUES("overlook", "눈감아주다", "1234");
INSERT INTO word VALUES("reinforce", "보강히다", "1234");
INSERT INTO word VALUES("accuse", "고발하다, 비난하다", "1234");
INSERT INTO word VALUES("restrict", "제한하다", "1234");
INSERT INTO word VALUES("attain", "달성하다", "1234");
INSERT INTO word VALUES("cherish", "소중히 하다", "1234");
INSERT INTO word VALUES("suspend", "중지하다, 매달다", "1234");
INSERT INTO word VALUES("inherit", "상속받다, 물려받다", "1234");
INSERT INTO word VALUES("bestow", "수여하다", "1234");
INSERT INTO word VALUES("undertake", "떠맡다, 착수하다", "1234");
INSERT INTO word VALUES("include", "포함하다", "1234");
INSERT INTO word VALUES("exclude", "제외하다", "1234");
INSERT INTO word VALUES("justify", "정당화하다", "1234");
INSERT INTO word VALUES("annoy", "괴롭히다", "1234");
INSERT INTO word VALUES("esteem", "존경, 존경하다", "1234");
INSERT INTO word VALUES("cure", "치료하다", "1234");
INSERT INTO word VALUES("resign", "사직하다, 단념하다", "1234");
INSERT INTO word VALUES("accurate", "정확한", "1234");
INSERT INTO word VALUES("rational", "합리적인", "1234");
INSERT INTO word VALUES("literate", "읽고 쓸 줄 아는", "1234");
INSERT INTO word VALUES("conservative", "보수적인", "1234");
INSERT INTO word VALUES("radical", "근본적, 급진적", "1234");
INSERT INTO word VALUES("pure", "순수한", "1234");
INSERT INTO word VALUES("queer", "별난, 기묘한", "1234");
INSERT INTO word VALUES("sane", "제 정신의", "1234");
INSERT INTO word VALUES("qenuine", "진짜의, 순수한", "1234");
INSERT INTO word VALUES("vague", "막연한", "1234");
INSERT INTO word VALUES("entire", "완전한, 전체의", "1234");
INSERT INTO word VALUES("absurd", "불합리한", "1234");
INSERT INTO word VALUES("lonely", "고독한", "1234");
INSERT INTO word VALUES("savage", "야만스러운", "1234");
INSERT INTO word VALUES("nuclear", "핵의", "1234");
INSERT INTO word VALUES("obscure", "무명의, 애매한", "1234");
INSERT INTO word VALUES("intricate", "복잡한", "1234");
INSERT INTO word VALUES("mortal", "죽을 운명의", "1234");
INSERT INTO word VALUES("vivid", "생생한, 발랄한", "1234");
INSERT INTO word VALUES("arrogant", "오만한", "1234");
INSERT INTO word VALUES("exotic", "이국풍의", "1234");
INSERT INTO word VALUES("extreme", "극단의", "1234");
INSERT INTO word VALUES("imperative", "피할 수 없는", "1234");
INSERT INTO word VALUES("mature", "성숙한", "1234");
INSERT INTO word VALUES("tight", "단단한", "1234");
INSERT INTO word VALUES("adequate", "적당한, 충분한", "1234");
INSERT INTO word VALUES("dissolute", "타락한", "1234");
INSERT INTO word VALUES("mutual", "서로의", "1234");
INSERT INTO word VALUES("splendid", "화려한", "1234");
INSERT INTO word VALUES("timid", "겁 많은", "1234");
INSERT INTO word VALUES("durable", "오래 견디는", "1234");
INSERT INTO word VALUES("conspicuous", "현저한", "1234");
INSERT INTO word VALUES("brisk", "활발한", "1234");
INSERT INTO word VALUES("primitive", "원시의", "1234");
INSERT INTO word VALUES("superficial", "피상적인", "1234");
INSERT INTO word VALUES("brilliant", "훌륭한", "1234");
INSERT INTO word VALUES("conscious", "의식적인", "1234");
INSERT INTO word VALUES("abstract", "추상적인", "1234");
INSERT INTO word VALUES("concrete", "구체적인", "1234");
INSERT INTO word VALUES("profound", "심오한", "1234");
INSERT INTO word VALUES("supreme", "최고의", "1234");
INSERT INTO word VALUES("trivial", "시시한, 하찮은", "1234");
INSERT INTO word VALUES("apparent", "명백한, 외관상의", "1234");
INSERT INTO word VALUES("thorough", "철저한", "1234");
INSERT INTO word VALUES("athletic", "운동경기의", "1234");
INSERT INTO word VALUES("absolute", "절대적인", "1234");
INSERT INTO word VALUES("meager", "여윈, 빈약한", "1234");
INSERT INTO word VALUES("sagacious", "현명한", "1234");
INSERT INTO word VALUES("plausible", "그럴듯한", "1234");
INSERT INTO word VALUES("potential", "잠재적인", "1234");
INSERT INTO word VALUES("unprecedented", "전례가 없는", "1234");
INSERT INTO word VALUES("robust", "건장한", "1234");
INSERT INTO word VALUES("ample", "충분한", "1234");
INSERT INTO word VALUES("akin", "동족의", "1234");
INSERT INTO word VALUES("cordial", "진심의", "1234");
INSERT INTO word VALUES("coarse", "조잡한, 야비한", "1234");
INSERT INTO word VALUES("vehement", "열정적인", "1234");
INSERT INTO word VALUES("venerable", "존경할 만한", "1234");
INSERT INTO word VALUES("compatible", "양립할 수 있는", "1234");
INSERT INTO word VALUES("weary", "피로한", "1234");
INSERT INTO word VALUES("complacent", "자기만족의", "1234");
INSERT INTO word VALUES("whimsical", "변덕스러운", "1234");
INSERT INTO word VALUES("corrupt", "썩은", "1234");
INSERT INTO word VALUES("wholesome", "건전한", "1234");
INSERT INTO word VALUES("credulous", "속기 쉬운", "1234");
INSERT INTO word VALUES("abrupt", "갑작스러운", "1234");
INSERT INTO word VALUES("devoid", "~이 없는", "1234");
INSERT INTO word VALUES("alien", "외국의", "1234");
INSERT INTO word VALUES("capricious", "변덕스러운", "1234");
INSERT INTO word VALUES("shabby", "초라한", "1234");
INSERT INTO word VALUES("dreary", "황량한", "1234");
INSERT INTO word VALUES("outstanding", "눈에 띄는", "1234");
INSERT INTO word VALUES("erroneous", "잘못된", "1234");
INSERT INTO word VALUES("pensive", "깊은 생각에 잠긴", "1234");
INSERT INTO word VALUES("forlorn", "고독한", "1234");
INSERT INTO word VALUES("gorgeous", "화려한", "1234");
INSERT INTO word VALUES("imprudent", "염치없는", "1234");
INSERT INTO word VALUES("pertinent", "적절한", "1234");
INSERT INTO word VALUES("frivolous", "경박한", "1234");
INSERT INTO word VALUES("genial", "따뜻한, 친절한", "1234");
INSERT INTO word VALUES("insolent", "오만한", "1234");
INSERT INTO word VALUES("indolent", "게으른", "1234");
INSERT INTO word VALUES("ruthless", "무자비한", "1234");
INSERT INTO word VALUES("incessant", "끊임없는", "1234");
INSERT INTO word VALUES("myriad", "무수한", "1234");
INSERT INTO word VALUES("legitimate", "합법적인", "1234");
INSERT INTO word VALUES("wistful", "탐내는 듯한", "1234");
INSERT INTO word VALUES("ultimate", "최후의, 궁극", "1234");
INSERT INTO word VALUES("initial", "처음의, 머리문자", "1234");
INSERT INTO word VALUES("solemn", "엄숙한", "1234");
INSERT INTO word VALUES("notorious", "악명 높은", "1234");
INSERT INTO word VALUES("sublime", "숭고한", "1234");
INSERT INTO word VALUES("immemorial", "태고의", "1234");
INSERT INTO word VALUES("constructive", "건설적인", "1234");
INSERT INTO word VALUES("destructive", "파괴적인", "1234");
INSERT INTO word VALUES("temporary", "임시의", "1234");
INSERT INTO word VALUES("contemporary", "같은 시대의", "1234");
INSERT INTO word VALUES("aloof", "따로 떨어져", "1234");
INSERT INTO word VALUES("indispensable", "필수의", "1234");
INSERT INTO word VALUES("jivenile", "청소년의", "1234");
INSERT INTO word VALUES("abnormal", "비정상적인", "1234");
INSERT INTO word VALUES("external", "외부의", "1234");
INSERT INTO word VALUES("rare", "드문, 진귀한", "1234");
INSERT INTO word VALUES("main", "주요한", "1234");
INSERT INTO word VALUES("complex", "복잡한", "1234");
INSERT INTO word VALUES("bold", "대담한", "1234");
INSERT INTO word VALUES("crude", "천연 그대로의", "1234");
INSERT INTO word VALUES("polite", "예의 바른, 공송한", "1234");
INSERT INTO word VALUES("current", "유행의, 현재의", "1234");
INSERT INTO word VALUES("severe", "엄격한, 격렬한", "1234");
INSERT INTO word VALUES("remote", "먼", "1234");
INSERT INTO word VALUES("deliberate", "신중한", "1234");
INSERT INTO word VALUES("separate", "분리된", "1234");
INSERT INTO word VALUES("physical", "물리적인, 물질의", "1234");
INSERT INTO word VALUES("eternal", "영원한", "1234");
INSERT INTO word VALUES("unique", "유일한, 독특한", "1234");
INSERT INTO word VALUES("transparent", "투명한", "1234");
INSERT INTO word VALUES("swift", "신속한", "1234");
INSERT INTO word VALUES("surplus", "과잉의", "1234");
INSERT INTO word VALUES("obstinate", "고집이 센", "1234");
INSERT INTO word VALUES("stubborn", "완고한", "1234");
INSERT INTO word VALUES("dense", "짙은, 빽빽한", "1234");
INSERT INTO word VALUES("familiar", "친한", "1234");
INSERT INTO word VALUES("shrewd", "영리한, 빈틈없는", "1234");
INSERT INTO word VALUES("remarkable", "현저한, 두드러진", "1234");
INSERT INTO word VALUES("puncutal", "시간을 지키는", "1234");
INSERT INTO word VALUES("terrible", "지독한", "1234");
INSERT INTO word VALUES("rude", "무례한", "1234");
INSERT INTO word VALUES("earnest", "열심인, 진지한", "1234");
INSERT INTO word VALUES("typical", "전형적인", "1234");
INSERT INTO word VALUES("sole", "유일한", "1234");
INSERT INTO word VALUES("fundamental", "근본적인", "1234");
INSERT INTO word VALUES("intense", "강렬한", "1234");
INSERT INTO word VALUES("essential", "본질적인, 필수의", "1234");
INSERT INTO word VALUES("distinct", "명백한, 명확한", "1234");
INSERT INTO word VALUES("particular", "특수한", "1234");
INSERT INTO word VALUES("subtle", "미묘한", "1234");
INSERT INTO word VALUES("ordinary", "보통의", "1234");
INSERT INTO word VALUES("vulgar", "천한, 상스러운", "1234");
INSERT INTO word VALUES("preeferable", "더 좋은", "1234");
INSERT INTO word VALUES("strict", "엄격한", "1234");
INSERT INTO word VALUES("naked", "나체의", "1234");
INSERT INTO word VALUES("feminie", "여성의", "1234");
INSERT INTO word VALUES("deficient", "부족한", "1234");
INSERT INTO word VALUES("tender", "부드러운, 상냥한", "1234");
INSERT INTO word VALUES("incurable", "불치의", "1234");
INSERT INTO word VALUES("infinite", "무한의", "1234");
INSERT INTO word VALUES("irresistible", "저항할 수 없는", "1234");
INSERT INTO word VALUES("barren", "불모의, 메마른", "1234");
INSERT INTO word VALUES("annual", "해마다의", "1234");
INSERT INTO word VALUES("precise", "정확한", "1234");
INSERT INTO word VALUES("native", "타고난", "1234");
INSERT INTO word VALUES("constant", "불변의, 끊임없는", "1234");
INSERT INTO word VALUES("concise", "간결한", "1234");
INSERT INTO word VALUES("moral", "도덕적인", "1234");
INSERT INTO word VALUES("delicate", "민감한", "1234");
INSERT INTO word VALUES("ambiguous", "애매한", "1234");
INSERT INTO word VALUES("neutral", "중립의", "1234");
INSERT INTO word VALUES("sacred", "신성한", "1234");
INSERT INTO word VALUES("resolute", "단호한", "1234");
INSERT INTO word VALUES("instructive", "교훈적인", "1234");
INSERT INTO word VALUES("unanimous", "만장일치의", "1234");
INSERT INTO word VALUES("decent", "고상한, 상당한", "1234");
INSERT INTO word VALUES("legal", "합법적인", "1234");
INSERT INTO word VALUES("ancient", "고대의", "1234");
INSERT INTO word VALUES("precious", "귀중한", "1234");
INSERT INTO word VALUES("stern", "엄한, 엄격한", "1234");
INSERT INTO word VALUES("tradition", "전통, 전설", "1234");
INSERT INTO word VALUES("patriotism", "애국심", "1234");
INSERT INTO word VALUES("religion", "종교", "1234");
INSERT INTO word VALUES("conscience", "양심", "1234");
INSERT INTO word VALUES("intellect", "지성", "1234");
INSERT INTO word VALUES("culture", "교양, 문화", "1234");
INSERT INTO word VALUES("civilization", "문명", "1234");
INSERT INTO word VALUES("prejudice", "편견, 선입견", "1234");
INSERT INTO word VALUES("instinct", "본능", "1234");
INSERT INTO word VALUES("privilege", "특권(을 주다)", "1234");
INSERT INTO word VALUES("impulse", "충동", "1234");
INSERT INTO word VALUES("virtue", "미덕, 장점", "1234");
INSERT INTO word VALUES("vice", "악덕, 단점", "1234");
INSERT INTO word VALUES("revolution", "혁명, 운행", "1234");
INSERT INTO word VALUES("stimulus", "자극", "1234");
INSERT INTO word VALUES("ambition", "야망, 염원", "1234");
INSERT INTO word VALUES("vanity", "허영심", "1234");
INSERT INTO word VALUES("envy", "시기, 부러움", "1234");
INSERT INTO word VALUES("jealousy", "질투", "1234");
INSERT INTO word VALUES("fatigue", "피로", "1234");
INSERT INTO word VALUES("passion", "정열", "1234");
INSERT INTO word VALUES("famine", "기근", "1234");
INSERT INTO word VALUES("calamity", "재난, 불행", "1234");
INSERT INTO word VALUES("individual", "개인", "1234");
INSERT INTO word VALUES("emotion", "정서, 감정", "1234");
INSERT INTO word VALUES("evolution", "진화, 발전", "1234");
INSERT INTO word VALUES("hypocrisy", "위선", "1234");
INSERT INTO word VALUES("character", "특징, 인격, 문자", "1234");
INSERT INTO word VALUES("method", "방법", "1234");
INSERT INTO word VALUES("psychology", "심리(학)", "1234");
INSERT INTO word VALUES("chivalry", "기사도", "1234");
INSERT INTO word VALUES("literature", "문학", "1234");
INSERT INTO word VALUES("responsibility", "책임", "1234");
INSERT INTO word VALUES("system", "조직, 체계, 제도", "1234");
INSERT INTO word VALUES("challenge", "도전", "1234");
INSERT INTO word VALUES("monotony", "단조로움", "1234");
INSERT INTO word VALUES("disagree", "불명예, 치욕", "1234");
INSERT INTO word VALUES("luxury", "사치", "1234");
INSERT INTO word VALUES("anachronism", "시대착오", "1234");
INSERT INTO word VALUES("conquest", "정복", "1234");
INSERT INTO word VALUES("siege", "포위공격", "1234");
INSERT INTO word VALUES("insight", "통찰력", "1234");
INSERT INTO word VALUES("panic", "공황, 당황", "1234");
INSERT INTO word VALUES("universe", "우주, 전 세계", "1234");
INSERT INTO word VALUES("criticism", "비평, 비판", "1234");
INSERT INTO word VALUES("influence", "영향", "1234");
INSERT INTO word VALUES("resistance", "저항", "1234");
INSERT INTO word VALUES("convenience", "편리", "1234");
INSERT INTO word VALUES("hardship", "고난", "1234");
INSERT INTO word VALUES("existence", "존재, 생존", "1234");
INSERT INTO word VALUES("fortitude", "인내, 용기", "1234");
INSERT INTO word VALUES("compromise", "타협(하다)", "1234");
INSERT INTO word VALUES("prosperity", "번영", "1234");
INSERT INTO word VALUES("comfort", "위안, 안락", "1234");
INSERT INTO word VALUES("sacrifice", "희생", "1234");
INSERT INTO word VALUES("superstition", "미신", "1234");
INSERT INTO word VALUES("sympathy", "동점, 공감", "1234");
INSERT INTO word VALUES("perseverance", "인내", "1234");
INSERT INTO word VALUES("disgust", "혐오", "1234");
INSERT INTO word VALUES("monopoly", "독점", "1234");
INSERT INTO word VALUES("species", "종류, 인류", "1234");
INSERT INTO word VALUES("moisture", "습기", "1234");
INSERT INTO word VALUES("solitude", "고독", "1234");
INSERT INTO word VALUES("candidate", "지원자, 후보자", "1234");
INSERT INTO word VALUES("environment", "환경", "1234");
INSERT INTO word VALUES("destiny", "운명", "1234");
INSERT INTO word VALUES("hindrance", "방해", "1234");
INSERT INTO word VALUES("property", "재산, 소유권", "1234");
INSERT INTO word VALUES("increase", "증가(하다)", "1234");
INSERT INTO word VALUES("decrease", "감소(하다)", "1234");
INSERT INTO word VALUES("courtesy", "예절", "1234");
INSERT INTO word VALUES("theory", "이론", "1234");
INSERT INTO word VALUES("medium", "매개, 중간", "1234");
INSERT INTO word VALUES("principle", "원리, 주의", "1234");
INSERT INTO word VALUES("shortcoming", "결점", "1234");
INSERT INTO word VALUES("crisis", "위기", "1234");
INSERT INTO word VALUES("policy", "정책, 방침", "1234");
INSERT INTO word VALUES("affection", "애정", "1234");
INSERT INTO word VALUES("homage", "경의", "1234");
INSERT INTO word VALUES("conceit", "자부심", "1234");
INSERT INTO word VALUES("hostility", "적의, 적개심", "1234");
INSERT INTO word VALUES("frustration", "좌절, 욕구불만", "1234");
INSERT INTO word VALUES("victory", "승리", "1234");
INSERT INTO word VALUES("triumph", "승리", "1234");
INSERT INTO word VALUES("hatred", "증오", "1234");
INSERT INTO word VALUES("purpose", "목적", "1234");
INSERT INTO word VALUES("fantasy", "공상, 환상", "1234");
INSERT INTO word VALUES("struggle", "분투, 노력", "1234");
INSERT INTO word VALUES("access", "접근", "1234");
INSERT INTO word VALUES("contempt", "경멸", "1234");
INSERT INTO word VALUES("convention", "회의, 인습", "1234");
INSERT INTO word VALUES("harmony", "조화", "1234");
INSERT INTO word VALUES("scorn", "경멸", "1234");
INSERT INTO word VALUES("comment", "주석, 논평", "1234");
INSERT INTO word VALUES("dignity", "위엄", "1234");
INSERT INTO word VALUES("mercy", "자비, 은총", "1234");
INSERT INTO word VALUES("cowardice", "겁, 비겁", "1234");
INSERT INTO word VALUES("logic", "논리학", "1234");
INSERT INTO word VALUES("eloquence", "웅변", "1234");
INSERT INTO word VALUES("pastime", "오락, 기분전환", "1234");
INSERT INTO word VALUES("talent", "재능", "1234");
INSERT INTO word VALUES("misery", "비참", "1234");
INSERT INTO word VALUES("modesty", "겸손", "1234");
INSERT INTO word VALUES("circumstance", "환경, 사정", "1234");
INSERT INTO word VALUES("quality", "질, 특질, 성질", "1234");
INSERT INTO word VALUES("quantity", "양", "1234");
INSERT INTO word VALUES("commerce", "상업", "1234");
INSERT INTO word VALUES("conception", "개념", "1234");
INSERT INTO word VALUES("identity", "신원, 동일성", "1234");
INSERT INTO word VALUES("legend", "전설", "1234");
INSERT INTO word VALUES("trick", "계략, 장난", "1234");
INSERT INTO word VALUES("wealth", "부, 재산", "1234");
INSERT INTO word VALUES("charity", "자비, 자선", "1234");
INSERT INTO word VALUES("fate", "운명", "1234");
INSERT INTO word VALUES("evidence", "증거", "1234");
INSERT INTO word VALUES("tension", "긴장", "1234");
INSERT INTO word VALUES("impression", "인상, 감명", "1234");
INSERT INTO word VALUES("elegy", "애가, 비가", "1234");
INSERT INTO word VALUES("strain", "긴장, 압박", "1234");
INSERT INTO word VALUES("bribe", "뇌물", "1234");
INSERT INTO word VALUES("fame", "명성", "1234");
INSERT INTO word VALUES("soul", "영혼, 사람", "1234");
INSERT INTO word VALUES("gratitude", "감사", "1234");
INSERT INTO word VALUES("sin", "죄", "1234");
INSERT INTO word VALUES("crime", "범죄", "1234");
INSERT INTO word VALUES("strategy", "전략, 전술", "1234");
INSERT INTO word VALUES("heritage", "유산", "1234");
INSERT INTO word VALUES("strife", "투쟁", "1234");
INSERT INTO word VALUES("pollution", "오염", "1234");
INSERT INTO word VALUES("industry", "근면, 산업", "1234");
INSERT INTO word VALUES("defect", "결점, 단점", "1234");
INSERT INTO word VALUES("sincerity", "성실", "1234");
INSERT INTO word VALUES("piety", "경건, 신앙심", "1234");
INSERT INTO word VALUES("adolescence", "청년기", "1234");
INSERT INTO word VALUES("phenomenon", "현상", "1234");
INSERT INTO word VALUES("account", "계산, 설명", "1234");
INSERT INTO word VALUES("emphasis", "강조", "1234");
INSERT INTO word VALUES("proportion", "비례, 비율", "1234");
INSERT INTO word VALUES("rumor", "소문(을 내다)", "1234");
INSERT INTO word VALUES("faculty", "능력", "1234");
INSERT INTO word VALUES("worship", "숭배(하다)", "1234");
INSERT INTO word VALUES("doctrine", "학설, 주의", "1234");
INSERT INTO word VALUES("pity", "연민, 유감", "1234");
INSERT INTO word VALUES("commodity", "상품, 일용품", "1234");
INSERT INTO word VALUES("distress", "고통", "1234");
INSERT INTO word VALUES("discount", "이야기, 담화", "1234");
INSERT INTO word VALUES("function", "기능, 역할", "1234");
INSERT INTO word VALUES("fallacy", "오류", "1234");
INSERT INTO word VALUES("violence", "폭력, 맹렬", "1234");
INSERT INTO word VALUES("appetite", "식욕, 욕구", "1234");
INSERT INTO word VALUES("revival", "부활", "1234");
INSERT INTO word VALUES("foundation", "기초", "1234");
INSERT INTO word VALUES("behavior", "행위, 태도", "1234");
INSERT INTO word VALUES("discipline", "훈련, 규율", "1234");
INSERT INTO word VALUES("poverty", "빈곤", "1234");
INSERT INTO word VALUES("threat", "협박, 위협", "1234");
INSERT INTO word VALUES("menace", "협박, 위협", "1234");
INSERT INTO word VALUES("plague", "전염병", "1234");
INSERT INTO word VALUES("capacity", "능력, 수용력", "1234");
INSERT INTO word VALUES("attitude", "태도", "1234");
INSERT INTO word VALUES("merit", "장점, 공적", "1234");
INSERT INTO word VALUES("astronomy", "천문학", "1234");
INSERT INTO word VALUES("despair", "절망", "1234");
INSERT INTO word VALUES("patience", "인내", "1234");
INSERT INTO word VALUES("confidence", "신용, 자신", "1234");
INSERT INTO word VALUES("enthusiasm", "열광", "1234");
INSERT INTO word VALUES("peril", "위험", "1234");
INSERT INTO word VALUES("livelihood", "생계, 살림", "1234");
INSERT INTO word VALUES("opportunity", "기회", "1234");
INSERT INTO word VALUES("ridicule", "조롱, 조소", "1234");
INSERT INTO word VALUES("liberty", "자유", "1234");
INSERT INTO word VALUES("spirit", "정신, 원기", "1234");
INSERT INTO word VALUES("traffic", "교통", "1234");
INSERT INTO word VALUES("remedy", "구제책, 요법", "1234");
INSERT INTO word VALUES("symptom", "징후", "1234");
INSERT INTO word VALUES("tyranny", "전제정치, 포학", "1234");
INSERT INTO word VALUES("prospect", "기대, 전망", "1234");
INSERT INTO word VALUES("credit", "신용, 명예", "1234");
INSERT INTO word VALUES("profit", "이익", "1234");
INSERT INTO word VALUES("oblivion", "망각", "1234");
INSERT INTO word VALUES("constitution", "헌법, 체격, 구성", "1234");
INSERT INTO word VALUES("extent", "범위, 정도", "1234");
INSERT INTO word VALUES("efficiency", "능률, 효력", "1234");
INSERT INTO word VALUES("genius", "천재", "1234");
INSERT INTO word VALUES("nightmare", "악몽", "1234");
INSERT INTO word VALUES("benefit", "이익, 은혜", "1234");
INSERT INTO word VALUES("reign", "통치, 군림", "1234");
INSERT INTO word VALUES("ruin", "파멸, 폐허", "1234");
INSERT INTO word VALUES("factor", "요인, 요소", "1234");
INSERT INTO word VALUES("vocation", "직업", "1234");
INSERT INTO word VALUES("contract", "계약(하다)", "1234");
INSERT INTO word VALUES("welfare", "복지", "1234");
INSERT INTO word VALUES("community", "사회", "1234");
INSERT INTO word VALUES("faith", "신앙, 신용", "1234");
INSERT INTO word VALUES("propaganda", "선전", "1234");
INSERT INTO word VALUES("thrift", "절약, 검약", "1234");
INSERT INTO word VALUES("melancholy", "우울(한)", "1234");
INSERT INTO word VALUES("temper", "기질, 기분", "1234");
INSERT INTO word VALUES("finance", "재정", "1234");
INSERT INTO word VALUES("significance", "의의, 중요성", "1234");
INSERT INTO word VALUES("notable", "유명한", "1234");
INSERT INTO word VALUES("potent", "강력한", "1234");
INSERT INTO word VALUES("dismal", "음침한", "1234");
INSERT INTO word VALUES("eccentric", "별난", "1234");
INSERT INTO word VALUES("predominant", "우세한", "1234");
INSERT INTO word VALUES("serene", "고요한, 화창한", "1234");
INSERT INTO word VALUES("sanitary", "위생의", "1234");
INSERT INTO word VALUES("petty", "작은", "1234");
INSERT INTO word VALUES("simultaneous", "동시의", "1234");
INSERT INTO word VALUES("prominent", "저명한", "1234");
INSERT INTO word VALUES("steep", "험한", "1234");
INSERT INTO word VALUES("prodigal", "낭비하는, 방탕한", "1234");
INSERT INTO word VALUES("prudent", "사려 깊은, 신중한", "1234");
INSERT INTO word VALUES("sullen", "시무룩한", "1234");
INSERT INTO word VALUES("righteous", "바른, 공정한", "1234");
INSERT INTO word VALUES("sterile", "메마른, 불모의", "1234");
INSERT INTO word VALUES("transient", "일시적인", "1234");
INSERT INTO word VALUES("rigid", "단단한, 엄격한", "1234");
INSERT INTO word VALUES("senior", "손위의; 연장자", "1234");
INSERT INTO word VALUES("quaint", "진기한", "1234");
INSERT INTO word VALUES("stupid", "어리석은", "1234");
INSERT INTO word VALUES("fatal", "숙명, 치명적인", "1234");
INSERT INTO word VALUES("fluent", "유창한", "1234");
INSERT INTO word VALUES("tolerable", "참을 수 있는, 상당한", "1234");
INSERT INTO word VALUES("mechanical", "기계의", "1234");
INSERT INTO word VALUES("elastic", "탄력 있는", "1234");
INSERT INTO word VALUES("upright", "똑바른, 정직한", "1234");
INSERT INTO word VALUES("permanent", "영구적인", "1234");
INSERT INTO word VALUES("hideous", "무서운", "1234");
INSERT INTO word VALUES("uniform", "일정한", "1234");
INSERT INTO word VALUES("ardent", "열렬한, 열심인", "1234");
INSERT INTO word VALUES("liable", "하기 쉬운", "1234");
INSERT INTO word VALUES("discreet", "사려 깊은", "1234");
INSERT INTO word VALUES("informal", "비공식의", "1234");
INSERT INTO word VALUES("daring", "대담한", "1234");
INSERT INTO word VALUES("frugal", "검소한, 알뜰한", "1234");
INSERT INTO word VALUES("aggressive", "공격적인, 적극적인", "1234");
INSERT INTO word VALUES("invalid", "허약한; 병자", "1234");
INSERT INTO word VALUES("actual", "현실의", "1234");
INSERT INTO word VALUES("holy", "신성한", "1234");
INSERT INTO word VALUES("sensitive", "민감한", "1234");
INSERT INTO word VALUES("periodical", "정기의", "1234");
INSERT INTO word VALUES("human", "인간의, 인간다운", "1234");
INSERT INTO word VALUES("numerous", "매우 많은", "1234");
INSERT INTO word VALUES("rapid", "빠른; 급류", "1234");
INSERT INTO word VALUES("inborn", "타고난", "1234");
INSERT INTO word VALUES("vain", "헛된", "1234");
INSERT INTO word VALUES("obvious", "명백한", "1234");
INSERT INTO word VALUES("idealistic", "이상주의적인", "1234");
INSERT INTO word VALUES("undaunted", "굽히지 않는", "1234");
INSERT INTO word VALUES("indifferent", "무관심한", "1234");
INSERT INTO word VALUES("timely", "적시의", "1234");
INSERT INTO word VALUES("prompt", "신속한, 즉시의", "1234");
INSERT INTO word VALUES("clumsy", "어색한", "1234");
INSERT INTO word VALUES("imperial", "제국의, 황제의", "1234");
INSERT INTO word VALUES("atomic", "원자의", "1234");
INSERT INTO word VALUES("intent", "열중한; 의지", "1234");
INSERT INTO word VALUES("private", "개인의; 병사", "1234");
INSERT INTO word VALUES("positive", "명백한, 적극적인", "1234");
INSERT INTO word VALUES("lofty", "숭고한", "1234");
INSERT INTO word VALUES("mental", "정신의", "1234");
INSERT INTO word VALUES("official", "공식의", "1234");
INSERT INTO word VALUES("humble", "겸손한, 하찮은", "1234");
INSERT INTO word VALUES("harsh", "거친, 가혹한", "1234");
INSERT INTO word VALUES("loyal", "충성스러운", "1234");
INSERT INTO word VALUES("pathetic", "측은한", "1234");
INSERT INTO word VALUES("liberal", "너그러운", "1234");
INSERT INTO word VALUES("perpendicular", "수직의", "1234");
INSERT INTO word VALUES("technical", "기술적인", "1234");
INSERT INTO word VALUES("medieval", "중세의", "1234");
INSERT INTO word VALUES("prime", "제일의", "1234");
INSERT INTO word VALUES("gloomy", "어두운, 우울한", "1234");
INSERT INTO word VALUES("partial", "부분a, 불공평한", "1234");
INSERT INTO word VALUES("stout", "튼튼한, 뚱뚱한", "1234");
INSERT INTO word VALUES("civil", "시민의, 국내의", "1234");
INSERT INTO word VALUES("exquisite", "정교한", "1234");
INSERT INTO word VALUES("local", "지방의", "1234");
INSERT INTO word VALUES("principal", "주요한; 교장", "1234");
INSERT INTO word VALUES("sinister", "불길한", "1234");
INSERT INTO word VALUES("previous", "이전의", "1234");
INSERT INTO word VALUES("prone", "하기 쉬운", "1234");
INSERT INTO word VALUES("silly", "어리석은", "1234");
INSERT INTO word VALUES("reverse", "반대의", "1234");
INSERT INTO word VALUES("slender", "가느다란", "1234");
INSERT INTO word VALUES("strenuous", "활기 찬", "1234");
INSERT INTO word VALUES("futile", "무익한", "1234");
INSERT INTO word VALUES("raw", "날것의, 미숙한", "1234");
INSERT INTO word VALUES("wicked", "사악한", "1234");
INSERT INTO word VALUES("sheer", "순전한", "1234");
INSERT INTO word VALUES("relative", "상대적인", "1234");
INSERT INTO word VALUES("hardy", "튼튼한", "1234");
INSERT INTO word VALUES("solid", "고체의, 견고한", "1234");
INSERT INTO word VALUES("rural", "시골의", "1234");
INSERT INTO word VALUES("sly", "교활한", "1234");
INSERT INTO word VALUES("sober", "진지한, 냉정한", "1234");
INSERT INTO word VALUES("stiff", "굳은, 뻣뻣한", "1234");
INSERT INTO word VALUES("tame", "길든; 길들이다", "1234");
INSERT INTO word VALUES("destitute", "빈곤한, 결핍한", "1234");
INSERT INTO word VALUES("tough", "단단한", "1234");
INSERT INTO word VALUES("steady", "한결같은", "1234");
INSERT INTO word VALUES("beckon","신호하다","1234");
INSERT INTO word VALUES("collapse","붕괴하다","1234");
INSERT INTO word VALUES("mar","상하게 하다","1234");
INSERT INTO word VALUES("kneel","무릎 꿇다","1234");
INSERT INTO word VALUES("pant","헐떡이다, 갈망v","1234");
INSERT INTO word VALUES("warrant","보증하다","1234");
INSERT INTO word VALUES("kindle","불을 붙이다","1234");
INSERT INTO word VALUES("uphold","지지하다, 돕다","1234");
INSERT INTO word VALUES("disdain","경멸하다; 경멸","1234");
INSERT INTO word VALUES("prescribe","규정v, 처방v","1234");
INSERT INTO word VALUES("accompany","동반v, 반주v","1234");
INSERT INTO word VALUES("abide","살다, 머무르다","1234");
INSERT INTO word VALUES("divide","나누다, 분할v","1234");
INSERT INTO word VALUES("paralyze","마비시키다","1234");
INSERT INTO word VALUES("contain","포함하다","1234");
INSERT INTO word VALUES("endow","기부하다, 주다","1234");
INSERT INTO word VALUES("guard","지키다; 수위","1234");
INSERT INTO word VALUES("crash","무너지다, 충돌v","1234");
INSERT INTO word VALUES("burst","폭발v, 파열v","1234");
INSERT INTO word VALUES("worry","걱정하다","1234");
INSERT INTO word VALUES("military","군대의, 육군의","1234");
INSERT INTO word VALUES("trustworthy","신뢰할 수 있는","1234");
INSERT INTO word VALUES("delicious","맛있는","1234");
INSERT INTO word VALUES("manifest","명백한; 명시v","1234");
INSERT INTO word VALUES("gradual","점진적인","1234");
INSERT INTO word VALUES("voluntary","자발적인","1234");
INSERT INTO word VALUES("stately","당당한","1234");
INSERT INTO word VALUES("proficient","숙달한","1234");
INSERT INTO word VALUES("tropical","열대의","1234");
INSERT INTO word VALUES("superfluous","여분의","1234");
INSERT INTO word VALUES("eminent","저명한, 뛰어난","1234");
INSERT INTO word VALUES("contrary","반대의; 반대","1234");
INSERT INTO word VALUES("feudal","봉건적인","1234");
INSERT INTO word VALUES("fertile","비옥한, 다산한","1234");
INSERT INTO word VALUES("intimate","친밀한","1234");
INSERT INTO word VALUES("primary","제일의, 주요한","1234");
INSERT INTO word VALUES("enormous","거대한","1234");
INSERT INTO word VALUES("disinterested","사심 없는, 공평한","1234");
INSERT INTO word VALUES("magnificent","웅대한, 장엄한","1234");
INSERT INTO word VALUES("similar","비슷한","1234");
INSERT INTO word VALUES("tranquil","조용한","1234");
INSERT INTO word VALUES("commonplace","평범한","1234");
INSERT INTO word VALUES("artificial","인공적인","1234");
INSERT INTO word VALUES("wretched","불쌍한, 비참한","1234");
INSERT INTO word VALUES("sovereign","최고의","1234");
INSERT INTO word VALUES("staple","주요한","1234");
INSERT INTO word VALUES("vital","생명의, 중요한","1234");
INSERT INTO word VALUES("moderate","알맞은, 중용의","1234");
INSERT INTO word VALUES("casual","우연한","1234");
INSERT INTO word VALUES("stable","안정된; 외양간","1234");
INSERT INTO word VALUES("royal","왕의, 왕위의","1234");
INSERT INTO word VALUES("tiny","몹시 작은","1234");
INSERT INTO word VALUES("sufficient","충분한","1234");
INSERT INTO word VALUES("tidy","단정한","1234");
INSERT INTO word VALUES("acute","날카로운","1234");
INSERT INTO word VALUES("subjective","주관적인","1234");
INSERT INTO word VALUES("ripe","익은","1234");
INSERT INTO word VALUES("arctic","북극의","1234");
INSERT INTO word VALUES("parallel","평행의, 유사한","1234");
INSERT INTO word VALUES("brief","짧은, 간결한","1234");
INSERT INTO word VALUES("slight","적은, 하찮은","1234");
INSERT INTO word VALUES("inevitable","불가피한","1234");
INSERT INTO word VALUES("perpetual","영원한, 끊임없는","1234");
INSERT INTO word VALUES("reckless","무모한","1234");
INSERT INTO word VALUES("vast","막대한","1234");
INSERT INTO word VALUES("immense","막대한","1234");
INSERT INTO word VALUES("tremendous","엄청난, 무서운","1234");
INSERT INTO word VALUES("innocent","순결한, 결백한","1234");
INSERT INTO word VALUES("divine","신성한, 비범한","1234");
INSERT INTO word VALUES("tedious","지루한","1234");
INSERT INTO word VALUES("domestic","가정의, 국내의","1234");
INSERT INTO word VALUES("huge","거대한","1234");
INSERT INTO word VALUES("colloquial","구어체의","1234");
INSERT INTO word VALUES("vacant","텅 빈, 멍한","1234");
INSERT INTO word VALUES("reluctant","싫어하는","1234");
INSERT INTO word VALUES("skeptical","회의적인","1234");
INSERT INTO word VALUES("awkward","어설픈, 귀찮은","1234");
INSERT INTO word VALUES("scanty","부족한","1234");
INSERT INTO word VALUES("inherent","타고난, 고유의","1234");
INSERT INTO word VALUES("extravagant","사치스러운","1234");
INSERT INTO word VALUES("aware","알고 있는","1234");
INSERT INTO word VALUES("ignoble","천한, 비열한","1234");
INSERT INTO word VALUES("shy","수줍어하는","1234");
INSERT INTO word VALUES("frank","솔직한","1234");
INSERT INTO word VALUES("spontaneous","자발적인","1234");
INSERT INTO word VALUES("visible","눈에 보이는","1234");
INSERT INTO word VALUES("inferior","열등한","1234");
INSERT INTO word VALUES("ashamed","부끄러워하는","1234");
INSERT INTO word VALUES("capable","유능한","1234");
INSERT INTO word VALUES("keen","날카로운","1234");
INSERT INTO word VALUES("exact","정확한","1234");
INSERT INTO word VALUES("utmost","최고의","1234");
INSERT INTO word VALUES("dumb","벙어리의","1234");
INSERT INTO word VALUES("fierce","사나운, 맹렬한","1234");
INSERT INTO word VALUES("faint","희미한, 약한","1234");
INSERT INTO word VALUES("affirmative","긍정적인","1234");
INSERT INTO word VALUES("guilty","유죄의","1234");
INSERT INTO word VALUES("firm","견고한, 단호한","1234");
INSERT INTO word VALUES("diverse","다양한","1234");
INSERT INTO word VALUES("plain","명백한, 검소한","1234");
INSERT INTO word VALUES("source", "원천, 출처");
INSERT INTO word VALUES("twilight", "황혼, 희미한 빛");
INSERT INTO word VALUES("fever", "열");
INSERT INTO word VALUES("relief", "구제, 구원, 안심");
INSERT INTO word VALUES("refuge", "피난처");
INSERT INTO word VALUES("experiment", "실험");
INSERT INTO word VALUES("expense", "비용, 희생");
INSERT INTO word VALUES("reliance", "신뢰");
INSERT INTO word VALUES("grief", "슬픔");
INSERT INTO word VALUES("effect", "결과, 효과, 영향");
INSERT INTO word VALUES("scope", "범위, 시야");
INSERT INTO word VALUES("habit", "습관");
INSERT INTO word VALUES("defense", "방어, 변호");
INSERT INTO word VALUES("aviation", "비행, 항공");
INSERT INTO word VALUES("navigation", "항해");
INSERT INTO word VALUES("resource", "자원, 지략");
INSERT INTO word VALUES("cruelty", "잔인");
INSERT INTO word VALUES("negligence", "태만");
INSERT INTO word VALUES("bliss", "환희, 행복");
INSERT INTO word VALUES("delay", "지체, 연기");
INSERT INTO word VALUES("contact", "접촉(하다)");
INSERT INTO word VALUES("poison", "독, 독약");
INSERT INTO word VALUES("awe", "두려운");
INSERT INTO word VALUES("nutrition", "영양");
INSERT INTO word VALUES("obligation", "의무, 은혜");
INSERT INTO word VALUES("reward", "보답, 보상");
INSERT INTO word VALUES("peer", "귀족, 동료, 응시하다");
INSERT INTO word VALUES("controversy", "논쟁");
INSERT INTO word VALUES("material", "물질, 재료");
INSERT INTO word VALUES("nationality", "국적, 국민성");
INSERT INTO word VALUES("majority", "대다수");
INSERT INTO word VALUES("personality", "개성, 유명인사");
INSERT INTO word VALUES("region", "지방");
INSERT INTO word VALUES("clue", "단서, 실마리");
INSERT INTO word VALUES("parliament", "의회");
INSERT INTO word VALUES("government", "정치, 정부");
INSERT INTO word VALUES("oath", "맹세, 서약");
INSERT INTO word VALUES("revenue", "세입");
INSERT INTO word VALUES("explanation", "설명");
INSERT INTO word VALUES("minister", "장관, 목사");
INSERT INTO word VALUES("obstacle", "장애물");
INSERT INTO word VALUES("majesty", "존엄");
INSERT INTO word VALUES("globe", "지구");
INSERT INTO word VALUES("pressure", "압력, 압박");
INSERT INTO word VALUES("standpoint", "입장, 견지");
INSERT INTO word VALUES("monument", "기념비, 기념물");
INSERT INTO word VALUES("opponent", "적");
INSERT INTO word VALUES("fiction", "소설, 허구");
INSERT INTO word VALUES("detail", "상세(히 말하다)");
INSERT INTO word VALUES("solution", "해결, 용해");
INSERT INTO word VALUES("maximum", "최대");
INSERT INTO word VALUES("communism", "공산주의");
INSERT INTO word VALUES("tide", "조수, 풍조");
INSERT INTO word VALUES("honesty", "정직");
INSERT INTO word VALUES("brute", "짐승");
INSERT INTO word VALUES("beast", "짐승 (같은 인간)");
INSERT INTO word VALUES("inspiration", "영감, 고취");
INSERT INTO word VALUES("harm", "해, 해치다");
INSERT INTO word VALUES("taste", "맛, 취미, 기호");
INSERT INTO word VALUES("independence", "독립");
INSERT INTO word VALUES("engagement", "약속, 약혼");
INSERT INTO word VALUES("rank", "지위, 계급");
INSERT INTO word VALUES("glacier", "빙하");
INSERT INTO word VALUES("prairie", "대초원");
INSERT INTO word VALUES("cradle", "요람, 발상지");
INSERT INTO word VALUES("incident", "사건");
INSERT INTO word VALUES("disillusion", "환멸");
INSERT INTO word VALUES("election", "선거");
INSERT INTO word VALUES("gesture", "몸짓");
INSERT INTO word VALUES("warfare", "전쟁");
INSERT INTO word VALUES("adventure", "모험");
INSERT INTO word VALUES("resort", "놀이터, 수단");
INSERT INTO word VALUES("situation", "위치, 상황");
INSERT INTO word VALUES("emigrant", "이주자");
INSERT INTO word VALUES("historian", "역사가");
INSERT INTO word VALUES("creature", "창조물, 생물");
INSERT INTO word VALUES("victim", "희생");
INSERT INTO word VALUES("delight", "즐거움");
INSERT INTO word VALUES("decay", "부패, 쇠퇴");
INSERT INTO word VALUES("admiral", "제독 (해군대장)");
INSERT INTO word VALUES("colony", "식민지");
INSERT INTO word VALUES("philosophy", "철학");
INSERT INTO word VALUES("treasure", "보물");
INSERT INTO word VALUES("admiration", "감탄");
INSERT INTO word VALUES("flesh", "살, 육체");
INSERT INTO word VALUES("conduct", "지휘자, 차장, 행위");
INSERT INTO word VALUES("aspect", "양상, 국면");
INSERT INTO word VALUES("anniversary", "기념일");
INSERT INTO word VALUES("laboratory", "실험실, 연구소");
INSERT INTO word VALUES("cell", "세포");
INSERT INTO word VALUES("area", "면적, 지역");
INSERT INTO word VALUES("symbol", "상징, 부호");
INSERT INTO word VALUES("assent", "동의, 동의하다");
INSERT INTO word VALUES("manuscript", "원고");
INSERT INTO word VALUES("mechanism", "기계장치, 기구");
INSERT INTO word VALUES("scent", "향기");
INSERT INTO word VALUES("donation", "기부(금), 기증");
INSERT INTO word VALUES("miracle", "기적");
INSERT INTO word VALUES("continent", "대륙");
INSERT INTO word VALUES("horror", "공포");
INSERT INTO word VALUES("essay", "수필");
INSERT INTO word VALUES("armament", "군비");
INSERT INTO word VALUES("fable", "우화");
INSERT INTO word VALUES("maxim", "격언");
INSERT INTO word VALUES("perspective", "가망, 전망");
INSERT INTO word VALUES("income", "수입");
INSERT INTO word VALUES("fortune", "운, 행운, 재산");
INSERT INTO word VALUES("aid", "도움");
INSERT INTO word VALUES("fuel", "연료");
INSERT INTO word VALUES("sigh", "한숨");
INSERT INTO word VALUES("fumiture", "가구");
INSERT INTO word VALUES("shelter", "피난처");
INSERT INTO word VALUES("view", "경치, 의견, 관점");
INSERT INTO word VALUES("navy", "해군");
INSERT INTO word VALUES("inability", "무능");
INSERT INTO word VALUES("territory", "영토");
INSERT INTO word VALUES("imitation", "모방");
INSERT INTO word VALUES("alternative", "양자택일");
INSERT INTO word VALUES("foliage", "나뭇잎");
INSERT INTO word VALUES("preface", "서문(머리말)");
INSERT INTO word VALUES("review", "복습, 평론");
INSERT INTO word VALUES("mischief", "장난, 손해");
INSERT INTO word VALUES("departure", "출발");
INSERT INTO word VALUES("surface", "표면, 표면의");
INSERT INTO word VALUES("funeral", "장례식");
INSERT INTO word VALUES("ignorance", "무지");
INSERT INTO word VALUES("popularity", "인기, 유행");
INSERT INTO word VALUES("pace", "걸음");
INSERT INTO word VALUES("merchandise", "상품");
INSERT INTO word VALUES("space", "공간, 우주");
INSERT INTO word VALUES("predecessor", "전임자, 선조");
INSERT INTO word VALUES("soil", "흙, 땅");
INSERT INTO word VALUES("hospitality", "환대");
INSERT INTO word VALUES("trait", "특색");
INSERT INTO word VALUES("traitor", "배반자, 반역자");
INSERT INTO word VALUES("puzzle", "수수께끼");
INSERT INTO word VALUES("riddle", "수수께끼");
INSERT INTO word VALUES("solace", "위안, 위로");
INSERT INTO word VALUES("vision", "시력, 통찰력");
INSERT INTO word VALUES("treachery", "배신, 반역");
INSERT INTO word VALUES("pasture", "목장, 목초지");
INSERT INTO word VALUES("renown", "명성");
INSERT INTO word VALUES("vessel", "(큰)배, 그릇");
INSERT INTO word VALUES("specimen", "표본, 실례");
INSERT INTO word VALUES("trace", "자국");
INSERT INTO word VALUES("slumber", "잠, 잠자다");
INSERT INTO word VALUES("harvest", "수확");
INSERT INTO word VALUES("tact", "재치, 요령");
INSERT INTO word VALUES("element", "원소, 요소");
INSERT INTO word VALUES("pang", "양심의 가책");
INSERT INTO word VALUES("flaw", "결점, 흠");
INSERT INTO word VALUES("riot", "폭동");
INSERT INTO word VALUES("folk", "사람들, 가족");
INSERT INTO word VALUES("temperance", "절제, 금주");
INSERT INTO word VALUES("garbage", "쓰레기, 찌꺼기");
INSERT INTO word VALUES("mob", "군중, 폭도");
INSERT INTO word VALUES("adult", "성인");
INSERT INTO word VALUES("temperament", "기질");
INSERT INTO word VALUES("expansion", "확장");
INSERT INTO word VALUES("output", "생산량");
INSERT INTO word VALUES("glance", "힐끗 봄");
INSERT INTO word VALUES("vein", "혈관, 정맥, 광맥");
INSERT INTO word VALUES("conclusion", "결말, 결론");
INSERT INTO word VALUES("revolt", "반역, 혐오");
INSERT INTO word VALUES("pessimist", "비관론자");
INSERT INTO word VALUES("reverie", "환상");
INSERT INTO word VALUES("mixture", "혼합물");
INSERT INTO word VALUES("outcome", "생산량");
INSERT INTO word VALUES("expert", "전문가");
INSERT INTO word VALUES("project", "계획, 내던지다");
INSERT INTO word VALUES("consequence", "결과, 중요성");
INSERT INTO word VALUES("rapture", "환희");
INSERT INTO word VALUES("pioneer", "개척자, 선구자");
INSERT INTO word VALUES("revenge", "복수, 원한");
INSERT INTO word VALUES("amount", "총계");
INSERT INTO word VALUES("repose", "휴식, 쉬다");
INSERT INTO word VALUES("author", "저자, 창시자");
INSERT INTO word VALUES("audience", "청중");
INSERT INTO word VALUES("throne", "왕위, 왕좌");
INSERT INTO word VALUES("outlook", "전망, ~관");
INSERT INTO word VALUES("expression", "표현, 표정");
INSERT INTO word VALUES("benefactor", "은인, 후원자");
INSERT INTO word VALUES("suburb", "교외, 변두리");
INSERT INTO word VALUES("apology", "사과, 변명");
INSERT INTO word VALUES("proposal", "제의, 신청");
INSERT INTO word VALUES("phase", "국면, 양상");
INSERT INTO word VALUES("male", "남자, 수컷");
INSERT INTO word VALUES("relish", "맛, 흥미");
INSERT INTO word VALUES("motive", "동기");
INSERT INTO word VALUES("summary", "요약");
INSERT INTO word VALUES("plot", "음모, 계획");
INSERT INTO word VALUES("relic", "유물");
INSERT INTO word VALUES("bronze", "청동");
INSERT INTO word VALUES("status", "지위, 현상");
INSERT INTO word VALUES("mystery", "신비");
INSERT INTO word VALUES("treason", "반역죄");
INSERT INTO word VALUES("trifle", "사소한 일");
INSERT INTO word VALUES("trend", "경향, 추세");
INSERT INTO word VALUES("spectacle", "광경, 안경");
INSERT INTO word VALUES("statue", "조각상");
INSERT INTO word VALUES("cliff", "절벽, 낭떠러지");
INSERT INTO word VALUES("trap", "덫, 함정");
INSERT INTO word VALUES("sermon", "설교");
INSERT INTO word VALUES("imagination", "상상력");
INSERT INTO word VALUES("omen", "전조, 조짐");
INSERT INTO word VALUES("diameter", "직경, 지름");
INSERT INTO word VALUES("effort", "노력");
INSERT INTO word VALUES("adversity", "역경");
INSERT INTO word VALUES("snare", "덫, 유혹");
INSERT INTO word VALUES("satisfaction", "만족");
INSERT INTO word VALUES("estate", "재산, 지위");
INSERT INTO word VALUES("orator", "웅변가");
INSERT INTO word VALUES("plea", "구실, 탄원");
INSERT INTO word VALUES("meadow", "목초지");
INSERT INTO word VALUES("shortage", "부족");
INSERT INTO word VALUES("activity", "활동");
INSERT INTO word VALUES("stage", "무대, 시기, 단계");
INSERT INTO word VALUES("decree", "명령, 포고");
INSERT INTO word VALUES("myth", "신화");
INSERT INTO word VALUES("hazzard", "위험, 우연");
INSERT INTO word VALUES("pattern", "모범, 모형");
INSERT INTO word VALUES("fluid", "액체, 유동성의");
INSERT INTO word VALUES("union", "결합, 일치");
INSERT INTO word VALUES("disciple", "제자");
INSERT INTO word VALUES("playwright", "극작가");
INSERT INTO word VALUES("truce", "휴전");
INSERT INTO word VALUES("cave", "동굴");
INSERT INTO word VALUES("feat", "공적");
INSERT INTO word VALUES("forest", "숲");
INSERT INTO word VALUES("friction", "마찰, 알력");
INSERT INTO word VALUES("digestion", "소화, 숙고");
INSERT INTO word VALUES("verse", "운문, 시");
INSERT INTO word VALUES("counsel", "의논, 충고");
INSERT INTO word VALUES("token", "표시, 증거");
INSERT INTO word VALUES("value", "가치, 존중하다");
INSERT INTO word VALUES("flavor", "맛, 향기");
INSERT INTO word VALUES("transition", "변천, 과도기");
INSERT INTO word VALUES("pause", "멈춤, 중지");
INSERT INTO word VALUES("healthen", "이교도, 이방인");
INSERT INTO word VALUES("worth", "가치, 가치가 있는");
INSERT INTO word VALUES("heretic", "이단자, 이교도");
INSERT INTO word VALUES("fund", "자금");
INSERT INTO word VALUES("bait", "미끼, 유혹");
INSERT INTO word VALUES("range", "범위, 산맥");
INSERT INTO word VALUES("orientation", "방향결정");
INSERT INTO word VALUES("elegance", "우아함");
INSERT INTO word VALUES("masterpiece", "걸작");
INSERT INTO word VALUES("stature", "키, 신장");
INSERT INTO word VALUES("retort", "말대꾸");
INSERT INTO word VALUES("metropolis", "수도, 중심지");
INSERT INTO word VALUES("layer", "층");
INSERT INTO word VALUES("volume", "책, 권, 다량");
INSERT INTO word VALUES("testimony", "증거, 증명");
INSERT INTO word VALUES("haven", "항구, 피난처");
INSERT INTO word VALUES("research", "연구, 조사");
INSERT INTO word VALUES("spot", "장소, 지점");
INSERT INTO word VALUES("seed", "씨, 종자");
INSERT INTO word VALUES("drudgery", "고된 일");
INSERT INTO word VALUES("reverence", "존경, 존경하다");
INSERT INTO word VALUES("summit", "정상");
INSERT INTO word VALUES("crust", "껍질");
INSERT INTO word VALUES("boss", "우두머리, 사장");
INSERT INTO word VALUES("agony", "고민");
INSERT INTO word VALUES("wisdom", "지혜");
INSERT INTO word VALUES("propriety", "예의 바름");
INSERT INTO word VALUES("physics", "물리학");
INSERT INTO word VALUES("timber", "목재");
INSERT INTO word VALUES("planet", "행성, 유성");
INSERT INTO word VALUES("design", "디자인, 계획");
INSERT INTO word VALUES("lung", "폐, 허파");
INSERT INTO word VALUES("leisure", "틈, 여가");
INSERT INTO word VALUES("organization", "조직, 단체");
INSERT INTO word VALUES("republic", "공화국");
INSERT INTO word VALUES("prosecution", "수행");
INSERT INTO word VALUES("torture", "고문");
INSERT INTO word VALUES("cottage", "오두막집");
INSERT INTO word VALUES("castle", "성");
INSERT INTO word VALUES("conference", "회의");
INSERT INTO word VALUES("tomb", "묘");
INSERT INTO word VALUES("fault", "결점, 잘못");
INSERT INTO word VALUES("magic", "마술");
INSERT INTO word VALUES("aim", "목적, 표적");
INSERT INTO word VALUES("sword", "검, 무력");
INSERT INTO word VALUES("risk", "위험");
INSERT INTO word VALUES("tool", "도구, 역할");
INSERT INTO word VALUES("weapon", "무기");
INSERT INTO word VALUES("vehicle", "탈 것, 차량");
INSERT INTO word VALUES("peculiarity", "특색, 버릇");
INSERT INTO word VALUES("contest", "투쟁, 경쟁");
INSERT INTO word VALUES("favor", "호의, 찬성");
INSERT INTO word VALUES("mankind", "인류");
INSERT INTO word VALUES("draft", "설계도, 초안");
INSERT INTO word VALUES("bomb", "폭탄");
INSERT INTO word VALUES("nerve", "신경");
INSERT INTO word VALUES("chemistry", "화학");
INSERT INTO word VALUES("addition", "부가");
INSERT INTO word VALUES("measure", "수단, 치수");
INSERT INTO word VALUES("vogue", "유행");
INSERT INTO word VALUES("reserve", "사양, 보존하다");
INSERT INTO word VALUES("occasion", "경우, 기회");
INSERT INTO word VALUES("dictator", "독재자");
INSERT INTO word VALUES("curiosity", "호기심");
INSERT INTO word VALUES("disorder", "무질서, 혼란");
INSERT INTO word VALUES("cast", "틀, 주조, 배역");
INSERT INTO word VALUES("cancer", "암");
INSERT INTO word VALUES("well-bing", "복지, 행복");
INSERT INTO word VALUES("chamber", "방");
INSERT INTO word VALUES("devil", "악마");
INSERT INTO word VALUES("barbarian", "야만인");
INSERT INTO word VALUES("stuff", "재료, 물건");
INSERT INTO word VALUES("scheme", "계획");
INSERT INTO word VALUES("legislation", "입법");
INSERT INTO word VALUES("symmetry", "균형, 조화");
INSERT INTO word VALUES("pomp", "화려");
INSERT INTO word VALUES("antiquity", "고대");
INSERT INTO word VALUES("malice", "악의, 원한");
INSERT INTO word VALUES("multitude", "다수");
INSERT INTO word VALUES("bent", "경향, 구부러진");
INSERT INTO word VALUES("creed", "신조, 주의");
INSERT INTO word VALUES("procedure", "수속, 진행");
INSERT INTO word VALUES("standard", "표준, 모범");
INSERT INTO word VALUES("boredom", "지루함");
INSERT INTO word VALUES("device", "고안, 장치");
INSERT INTO word VALUES("greed", "탐욕");
INSERT INTO word VALUES("contagion", "전염");
INSERT INTO word VALUES("satire", "풍자");
INSERT INTO word VALUES("hypothesis", "가설");
INSERT INTO word VALUES("proposition", "명제, 제의");
INSERT INTO word VALUES("perfume", "향수, 향기");
INSERT INTO word VALUES("miniature", "축소지도, 모형");
INSERT INTO word VALUES("bond", "속박");
INSERT INTO word VALUES("providence", "섭리, 신의 뜻");
INSERT INTO word VALUES("compassion", "동정");
INSERT INTO word VALUES("domain", "영토");
INSERT INTO word VALUES("caricature", "풍자만화");
INSERT INTO word VALUES("anguish", "고민, 고뇌");
INSERT INTO word VALUES("facility", "손쉬움, 설비");
INSERT INTO word VALUES("hygiene", "위생");
INSERT INTO word VALUES("conspiracy", "음모, 공모");
INSERT INTO word VALUES("accordance", "일치, 조화");
INSERT INTO word VALUES("ecstasy", "황홀");
INSERT INTO word VALUES("censure", "비난, 비난하다");
INSERT INTO word VALUES("allowance", "급여, 허가");
INSERT INTO word VALUES("campaign", "운동, 전쟁");
INSERT INTO word VALUES("canal", "운하");
INSERT INTO word VALUES("appratus", "기구, 기계");
INSERT INTO word VALUES("defiance", "도전, 무시");
INSERT INTO word VALUES("craft", "기능, 배, 비행기");
INSERT INTO word VALUES("patent", "특허");
INSERT INTO word VALUES("countenance", "표정, 안색");
INSERT INTO word VALUES("pulse", "맥박");
INSERT INTO word VALUES("implement", "기구, 도구");
INSERT INTO word VALUES("insurance", "보험, 보증");
INSERT INTO word VALUES("catastrophe", "파국, 재난");
INSERT INTO word VALUES("accident", "사건, 사고, 우연");
INSERT INTO word VALUES("district", "구역");
INSERT INTO word VALUES("direction", "방향, 지시");
INSERT INTO word VALUES("textile", "직물");
INSERT INTO word VALUES("organ", "기관");
INSERT INTO word VALUES("blood", "혈액");
INSERT INTO word VALUES("ray", "광선");
INSERT INTO word VALUES("crop", "농작물, 수확");
INSERT INTO word VALUES("drought", "가뭄");
INSERT INTO word VALUES("skin", "피부");
INSERT INTO word VALUES("bone", "뼈");
INSERT INTO word VALUES("interest", "이익, 흥미, 관심");
INSERT INTO word VALUES("limit", "제한, 제한하다");
INSERT INTO word VALUES("haste", "서두름");
INSERT INTO word VALUES("bless", "축복하다");
INSERT INTO word VALUES("irritate", "화나게 하다");
INSERT INTO word VALUES("prolong", "연장하다");
INSERT INTO word VALUES("postpone", "연기하다");
INSERT INTO word VALUES("co-operate", "협력하다");
INSERT INTO word VALUES("refer", "언급하다, 참조하다");
INSERT INTO word VALUES("permit", "허가하다");
INSERT INTO word VALUES("exaggerate", "과장하다");
INSERT INTO word VALUES("emerge", "나타나다");
INSERT INTO word VALUES("equip", "갖추다");
INSERT INTO word VALUES("ornament", "장식하다");
INSERT INTO word VALUES("furnish", "공급하다");
INSERT INTO word VALUES("advance", "전진하다");
INSERT INTO word VALUES("embark", "시작하다");
INSERT INTO word VALUES("flourish", "번창하다");
INSERT INTO word VALUES("deprive", "빼앗다");
INSERT INTO word VALUES("diminish", "감소하다");
INSERT INTO word VALUES("derive", "~을 얻다, 유래하다");
INSERT INTO word VALUES("exchange", "교환하다");
INSERT INTO word VALUES("rejoice", "기뻐하다");
INSERT INTO word VALUES("promote", "촉진하다, 승진시키다");
INSERT INTO word VALUES("nourish", "기르다");
INSERT INTO word VALUES("inquire", "묻다, 조사하다");
INSERT INTO word VALUES("ascertain", "확인하다");
INSERT INTO word VALUES("swear", "맹세하다");
INSERT INTO word VALUES("celebrate", "축하하다");
INSERT INTO word VALUES("marvel", "놀라다, 감탄");
INSERT INTO word VALUES("pray", "기도하다");
INSERT INTO word VALUES("reflect", "반사하다");
INSERT INTO word VALUES("ascend", "올라가다");
INSERT INTO word VALUES("descend", "내려가다");
INSERT INTO word VALUES("mention", "말하다");
select * from word;
select count(*) from word;